### ISSUE TITLE
chap-challenge-amarelo のレビュー

### ISSUE THREAD

**Issue by tetsunosuke** [engineers-lt/rooting-book-2#18]
読み始めました。気づいたところを挙げてみました。
意図と違ったらもちろんスルーしてください。

@amarelo-n24 

https://github.com/engineers-lt/rooting-book-2/blob/3748eb4dbb9c9757cf0b90ed86523f91aaa3b921/src/chap-challenge-amarelo.re#L11

強味 → 強み
https://twitter.com/mainichi_kotoba/status/856635356581552128

https://github.com/engineers-lt/rooting-book-2/blob/master/src/chap-challenge-amarelo.re#L62
しかし、〜が、と続いていくとわかりにくくなりそう。
行きましたが→行きました。 で良いかも。

https://github.com/engineers-lt/rooting-book-2/blob/master/src/chap-challenge-amarelo.re#L72
出の → での？

https://github.com/engineers-lt/rooting-book-2/blob/master/src/chap-challenge-amarelo.re#L190
調べたら一応、YouTuber表記が正しいようです

https://github.com/engineers-lt/rooting-book-2/blob/master/src/chap-challenge-amarelo.re#L194
「その機会」の「その」が何を表すのか曖昧だったので明記するといいと思いました

https://github.com/engineers-lt/rooting-book-2/blob/master/src/chap-challenge-amarelo.re#L202
未来に向けた挑戦し続けます　→ 未来に向けて挑戦し続けます
かな？

**Comment by oyakata2438** [comment]
危機感と、歩き始める過程がわかってよかったです。
あと、唐突に差し込まれるコーヒー話。

だいぶ細かいところばかりかもしれませんが、読みやすくする工夫として、ご参考まで。
L39
一番イケてなかったのは、客先常駐の4年、であれば、そう書いた方が良い。現所属企業が４+4+6あり、そのどこに当てはまるのかがわからないので。

L44
？理解した上で取り組んでいない
◯（あまり、全然？）理解せず取り組んでいました。

L45
基本情報の取得がプラスなのかマイナスなのかが今ひとつ不明なので、
取ったけれど、それが生かされるでもなく。。。のような表現の方が唐突感がないです。

L57
4.2.2`現所属企業に移動して〜 1文が長すぎます。たとえば、
〜にアサインされました。この時、周りの〜
とかにした方がスムーズです。

L59
半年で終わったのは、プロジェクトが終わった？状況が終わった？自分の意識が変わって、落ち着いた？

L82
終わった直後は〜と思うものの、〜な実感はない、そんな感触です。そんな時、アウトプットと〜
など、

L137
箇条書きの文末と一致してません。

具体的に実現したいと考えていることは、
・コーヒーの知見を公開するWebサイトを作る
・自分のコーヒー焙煎に役立つ仕組みを作る
などの方が良いと思います。

＝
以上、ご参考までー

**Comment by yumemi-dendo** [comment]
現状への葛藤と、少しでも自分から変えていこうとしたその軌跡が想いのままに綴られていて面白かったです。
まずは一歩を踏み出そうという強いメッセージ性が感じられました。


いくつか細かいところを含め気になるところを上げましたので、よければご参考ください。

L13
ここだけ全角のダブルクォートで挑戦という文字を囲っていますがpdfで見ると違和感があるので、直前の二箇所が「」で囲っているので統一するか強調したいなら太文字にするのがいいかと思います。（後半だと太文字で強調している？）

L33~36
箇条書きに句点（。）がついてるものとついてないものがあるので統一してください。

L46
「使い物にならないと思ったのか」→「使い物にならないと思われたのか」

L48
なぜ「キャリアを諦めた」のか直前の文では理由がうまく伝わってこなかったので、軽くでいいので掘り下げて欲しいです。
（使い物にならないと判断されたと思い、やる気がなくなったから、など）

L53
「そして今に至りますが」だと前文に対する否定的な文なので、「そう言った取り組みをしているうちに次第に」など前向きな文にした方が良いと思います。

L57~58
一文が長いので２、３文に分割した方が読みやすくなると思います。

L61
「知識・技術を習得して」と「勉強してスキルを上げたい」がかぶってしまっているので、「周囲のエンジニアに負けたくない」から「勉強して知識や技術を習得してスキルを上げたい」という書き方の方がスマートかと思います。

L62
誰がどう言った目的のために勉強会などのネタを探しているのかわからないので追記してください。

L105
毎回イベントの度に登壇しているように見えるので、そうでなければ「この「エンジニアの登壇を応援する会」ではたびたび登壇させていただき、」のように頻度を明記した方がわかりやすいです。

L201
「新型コロナウイルスのせいで外出すらままならないこの状態ですが」→「新型コロナウイルスのせいで外出すらままならない状態ですが」
「この」の内容を直前で説明しているため不要です。

L198~203
まとめの内容が複数あるのにも関わらず一段落で書いてしまっているので、いくつかに分割した方が良いかと思います。

**Comment by amarelo-n24** [comment]
たくさんのご指摘をいただきありがとうございました！にも関わらず、皆さんの原稿をレビューできず申し訳ありません！！

いただいた指摘箇所をすべて反映しました。また、追記もしましたので、お手数ですが再度レビューお願いします！
