### ISSUE TITLE
chap-challenge-maiameaのレビュー

### ISSUE THREAD

**Issue by tetsunosuke** [engineers-lt/rooting-book-2#19]
読み始めて気になったことをコメントしておきます。
趣旨と違ったらスルーしてください

@maiamea 

https://github.com/engineers-lt/rooting-book-2/blob/master/src/chap-challenge-maiamea.re#L103
おっしゃられていた　が二重敬語になるので、「おっしゃっていた」で良いと思います。

https://github.com/engineers-lt/rooting-book-2/blob/master/src/chap-challenge-maiamea.re#L88
ただ義務化してしまうと私の場合、途端に書けなくなってしまうので
句点の位置は、
ただ義務化してしまうと、私の場合途端に書けなくなってしまうので
のほうが良いかなと感じました。

**Comment by oyakata2438** [comment]
蛇足かもしれませんが・・・
「踏み出して」からのチャレンジがよくわかって、すごく良い記事だったと思います。
迷ってる人に、「一歩先に」挑戦した人からのアドバイスとして、等身大で、わかるー、となると思いました。それぞれのチャレンジ一つ一つはそこそこハードル低いですしね。

以下、ちょっと気になったとこ。
参考になれば幸いですし、読み捨ててもらっても構いませんー

・L15
投稿したきっかけの話で、させていただく、が重なりすぎな気がします。
挑戦の章でもあり、自分が選んだことにはもっと自信を持って、させていただきました、ではなく、やることにしました。とかがいいと思います。

・L101 文末、35P、とあるが、一瞬意味がわからないので、
Referenceとして打つなら、
エンジニアの登壇を応援する本、P35
とする方が良いと思います。

・L108 つよつよエンジニアの方が読みやすいと思います。強強エンジニアだと、一瞬読み方が出てきませんでした。

・せっかく「本を書く」「文章を寄稿する」というチャレンジを「この本で」やったので、
それに至る経緯、この執筆で悩んだこと、やってみて感じたことなどを書いてはいかがでしょう？

・アウトプットがもたらしたこと、まとめ、最後に、
いずれも「まとめ」です。分割するには少しそれぞれの量が少ないと思います。
まとめ、最後に、いずれも、章タイトルとして陳腐なので、アウトプットがもたらしたこと、で３段落まとめて良いと思います。

・参考文献が、登援本以外、各サービスのポータルで、参考文献になってません。
自分がやっている記事の紹介をするなら、自分の記事のトップサイトを示す、
他の人の記事等できっかけになったものを示すなら、それぞれの章でFootnoteで入れる、
単純に、「アウトプット先として良いですよ」という話なら、それぞれの章でFootnoteでリンクを貼る、
が良いと思います。

以上、ご参考までー

**Comment by yumemi-dendo** [comment]
この章の目的や伝えたいメッセージが明確でターゲットを絞っているのはとても上手い方法だなと感じました。
自分が読んでいてもいくつも共感するところがあると同時に、自分との比較をして「こんな歩き方をしている人もいるんだ」と興味深く読ませていただきました。

いくつか気になるところを以下に挙げさせていただきました。
指摘がこの章の主軸とズレるようでしたらスルーしてください。

L45
「ハードルの低いと感じるものから取り組むことで」→「ハードルが低いと感じるものから取り組むことで」

L60
「自分では考えつかない様々な価値観に触れることができます。」→「簡単なことからツイートをするのはオススメです。」の繋がりがどちらかと言えばいろんな方をフォローする事による効果だと思うので、適していないように感じます。
直前の文はツイートすることがオススメな理由にするか、もしくはTwitterを始める利点みないなまとめ方にする方が良いかと思います。

L66
「申込みを決断するのに数日、時間を要しました。」→「申込みを決断するのに数日間の時間を要しました。」
「時間を要した」という期間を示す文なので「数日間」という単語にした方が良いです。

L103
できれば登壇して感じたことや変わったことなどを掘り下げて欲しいです。
発表したことでゴールとなってしまい話が終わっていて、それがどのようにアウトプットへの苦手意識の克服につながったのかが伝わってこず、もったいなく感じました。
（登壇で失敗して二度とやりたくないって思う方も世の中にはいますので、登壇してみて何が良かったのかを書けるといいのかなと思います。）
