### ISSUE TITLE
chap-challenge-tetsunosukeのレビュー

### ISSUE THREAD

**Issue by yumemi-dendo** [engineers-lt/rooting-book-2#23]
挑戦の連続や経験・知識の違いからなる解答の構築方法についてなど、とても丁寧に書かれており勉強になりました。
またロールプレイの話は自分もよくやっているので納得しながら読んでいました。
全体的に必要なことが過不足なくまとめられていて、また文章の書き方も上手でとても読みやすかったです。

読んでいて気になったところを以下にいくつか挙げさせていただきました。
文章の主軸とズレるようでしたらスルーしていただいて構いません。

L26
完全に好みなのですが、以下のようにすると「学生時代の学び」と「これから先の生涯学習」で対比になるので文章がいい感じにスマートになるかと思います。
「これから先の「生涯学習」は~」→「これから先の人生における「生涯学習」は」

L164
「正解のない時代、というよりは正解のない時代。」
勘違いだったら申し訳ないのですが、これあってますか？

**Comment by tetsunosuke** [comment]
@yumemi-dendo ありがとうございました！

L26 はちょっとだけ表現を変えました。対比構造にするほどは文章が厚くはなかったので、微修正。

**Comment by tetsunosuke** [comment]
マージ済み閉じ忘れてました
