### ISSUE TITLE
chap-decision-oyakataのレビュー

### ISSUE THREAD

**Issue by DddEndow** [engineers-lt/rooting-book-2#24]
ご自身の体験から来るふりかえりと学びが凝縮されていて、とても面白かったです。
思いつきをどのように成長していくのか、またそれをコミュニティの成長というノウハウがなかなかない分野で文章化されていて勉強になりました。

読んでいて気になったところを以下にいくつか挙げさせていただきました。  
文章の主軸とズレるようでしたらスルーしていただいて構いません。

L14（完全に自分の好みです。）
「9.1.1 いくつかの思いつきと転機」は前節、一つ目の転機、二つ目の転機、その後と言った構成になっているかと思いますが、それぞれの転機の段落の区切りが少々読みづらいので、=４つか//blanklineを使うなどして区切りを明確にしていただけると助かります。
またL23, 27で文頭に「その後」という単語が連続して使用されているので、それを避けるのにも役立つかと思います。

L55
「法律や人道に触れる場合はその旨指摘してくれるでしょう。」→「法律や人道に触れる場合はその旨`を`指摘してくれるでしょう。」

**Comment by oyakata2438** [comment]
修正しました。
あとのページ区切りの関係で、====だと後ろが玉突きで追い出されて次ページに1行だけとかになっちゃうので・・・
Bold+普通文で若干強調して、という形にしてみましたー。
L55 は修正。
